config/routes.rb
V1foodoo::Application.routes.draw do
  devise_for :users

  resources :searches, only: [:new, :index]
  resources :restaurants
  resources :follows

  resources :choices

  resources :lists

  resources :users, :only => [:index, :show]

  root 'lists#new'
  post 'restaurants/:id' => 'restaurants#show'
  match 'searches/new' => 'searches#new', via: [:get, :post]
  get 'restaurant' => 'restaurants#show'
  post 'lists/create' => 'lists#create'
  get 'user/list' => 'user#list'
  get '/mylist' => 'lists#mylist'
  get 'lsearch' => 'users#index'
  post 'users/getall' =>  'users#getall'
  post 'favorite' => 'restaurants#favorite'
  post 'remove' => 'restaurants#remove'
  post 'searches/set_user_location' => 'searches#set_user_location'
  get 'searches/group' => 'searches#group'
  post 'users/address_input' => 'users#address_input'
  get 'restaurants' => 'restaurants#index'
  post '/address_input' => 'restaurants#address_input'
  post 'lists/add_curated' => 'lists#add_curated'
  post 'lists/rate' => 'lists#rate'

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<!-- logo -->
<a class="brand" id="brand">Foodoo</a>

<% if user_signed_in? %>
<!-- pages -->
<ul class="nav pull-right">
    <li><%= link_to('Pick', new_search_path, :method=>'get', :class => 'pick_nav') %></li>
    <li><%= link_to('List', restaurants_path, :method=>'get', :class => 'list_nav') %></li>
    <li><%= link_to('Add', new_list_path, :class => 'add_nav') %></li>
    <li><%= link_to('Tastebuddies', '/lsearch', :class => 'friend_nav') %></li>
</ul>
<!-- user settings -->
<ul class="nav settings">
  <li><%= link_to('Edit account', edit_user_registration_path) %></li>
  <li><%= link_to('Logout', destroy_user_session_path, :method=>'delete') %></li>
</ul>

<!-- user not signed in -->
<% else %>
<!-- user setup -->
<ul class='nav pull-right'>
  <li><%= link_to('Login', new_user_session_path) %></li>
  <li><%= link_to('Sign up', new_user_registration_path) %></li>
</ul>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Foodoo" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Bootstrap" %>">
    <%= stylesheet_link_tag "application", :media => "all", cache: true %>
    <%= javascript_include_tag "application", cache: true %>
    <%= csrf_meta_tags %>
    <%= include_gon %>
  </head>
  <body>
    <div class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </div>
    </div>
    <main role="main">
      <div class="container vidwrap">
        <%= render 'layouts/messages' %>
        <%= yield %>
        <footer>
        </footer>
      </div>
    </main>
  </body>
</html>